### ISSUE TITLE
Round 7 - Daily Intake Report - Camera

### ISSUE THREAD

**Issue by rsial2** [nasa/NTL-ISS-Food-Intake-Tracker#10]
When the camera button is pressed, the blue box that has "Snap a Photo" and Scan Barcode" has a little triangle in the top right corner that points to the pencil tool.  It should be pointing to the camera button. Similarly with the pen/search button, when that is tapped, the little triangle should point to that icon (and not the water icon).

**Comment by szwart** [comment]
Fixed.
