### ISSUE TITLE
Round 7 - Food Inventory - Nutrient Content

### ISSUE THREAD

**Issue by rsial2** [nasa/NTL-ISS-Food-Intake-Tracker#11]
When sorting by nutrient content, can we keep any filters that are clicked?  For example, if I want to get a list of Meat / Fish items that are sorted by sodium content, I would like to click Meat / Fish on the left and then Sort By Nutrient Content.  Right now, if I sort by nutrient content, all foods appear.

**Comment by szwart** [comment]
Fixed.
