### ISSUE TITLE
Round 7 - Daily Intake Report - Character Updates

### ISSUE THREAD

**Issue by rsial2** [nasa/NTL-ISS-Food-Intake-Tracker#12]
1. Change pkg to Pkg
2. Change gr (grams) to g

**Comment by szwart** [comment]
When a food is displayed in the Daily Intake Report and I swipe to the left over the nutrient content of that food, the protein, carb, and fat are still displayed as gm instead of g.  Also, when sorting foods by protein, carb, or fat in the Food Inventory, they still appear as gm instead of g.

**Comment by rsial2** [comment]
Working on this!

CC @coderReview

**Comment by rsial2** [comment]
@szwart, this defect has been fixed. Please delete the old version and re-install from the same install link.

**Comment by rsial2** [comment]
Hi @szwart, just checking in. Can we close this?

**Comment by szwart** [comment]
Fixed.
