### ISSUE TITLE
Round 7 - Daily Intake Report - Button Updates

### ISSUE THREAD

**Issue by rsial2** [nasa/NTL-ISS-Food-Intake-Tracker#18]
1. The icon for the delete button should be a native iOS icon (if you look in the Notes app of the iPad, use that icon for delete.

2. The icon for the copy button should be a native iOS icon 

3. The icon for the paste button should be a native iOS icon

4. The icon next to Add Food should be a + icon instead of the check with a circle around it.

**Comment by szwart** [comment]
I need to make a correction to #4 above - that should be the icon of a folder with a + on it (this is the one I emailed to Rashid).

**Comment by rsial2** [comment]
@szwart, the .jpeg you sent me isn't suitable to be used as an icon. It's not in the correct format, doesn't match the design and is not a high resolution. Do you mind if we use one of the native icons for 4?

**Comment by szwart** [comment]
That should work – thanks!

**Comment by rsial2** [comment]
Hi @szwart, if we change the icons (which we custom designed for ISS FIT), the native icons from Apple don't include colors. So we'd need to custom design them again.

The question about the color change is related to #17 

How do you want to handle this? I think the icons are very clear right now. Most iOS apps have their own custom icons, and vary rarely do they use the native icons. Most Apple built apps use the Apple icons - but not apps built by companies / individuals other than Apple. 

CC: @coderReview

**Comment by szwart** [comment]
The most important thing is to get rid of the red color on the trash can. Can that be done?



On Apr 11, 2015, at 10:54 AM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @szwart<https://github.com/szwart>, if we change the icons (which we custom designed for ISS FIT), the native icons from Apple don't include colors. So we'd need to custom design them again.

The question about the color change is related to #17<https://github.com/nasa/NTL-ISS-Food-Intake-Tracker/issues/17>

How do you want to handle this? I think the icons are very clear right now. Most iOS apps have their own custom icons, and vary rarely do they use the native icons. Most Apple built apps use the Apple icons - but not apps built by companies / individuals other than Apple.

CC: @coderReview<https://github.com/coderReview>

**Comment by rsial2** [comment]
@coderReview please confirm

**Comment by coderReview** [comment]
All icons used came from a prototype. They cannot be modified. Do you have the Photoshop source?

**Comment by rsial2** [comment]
Yes, please see: https://github.com/nasa/NTL-ISS-Food-Intake-Tracker/tree/master/App%20Documentation/Storyboards

**Comment by szwart** [comment]
Fixed
