### ISSUE TITLE
Round 8 - Snap a Photo - Remove Requirement to Add Food Name

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#22]
After a photo is taken, a result box with the picture appears. Please take away the requirement to add a food name. Also, once the user taps the Add to Consumption button, bring the user directly to the Daily Intake Report screen instead of having the extra "Food Added" screen that asks if the user wants to View Summary or Take Another Photo.

**Comment by coderReview** [comment]
@szwart, @rsial2, I cannot save to the database without a food name. If the food has no name the application will not work properly. What I could do is create an random name or something similar.
About the other request, no probem.

**Comment by szwart** [comment]
OK - how something similar to when a voice recording is done.  It just lists as "Intake from Voice".  Maybe a photo could be "Intake from Photo" if the user chooses to not enter a food name.

**Comment by coderReview** [comment]
The difference is that after a food is added, it's inserted in the database food list and can be added again. A voice recording is added only once and cannot be added again, only with another voice recording. If you don't want to allow the food to be added again, I could use something like "Intake from Photo". But this isn't a a minor adjustment to the code and would take at least a 5-7 days to implement.

**Comment by szwart** [comment]
Copy.  We do not think that a user will take a photo and use it again in the food inventory (it won't have nutrient content associated with it), so we don't think it is necessary to allow the food to be added again.  This is something we would like to keep on our wish list for the next round of fixes if/when we get more funds.

**Comment by rsial2** [comment]
@coderReview, what if we did this:
1. User can add food name or not. Basically, we don't require them to do it.
2. If they don't add the food name, in the DB, we save it as "Intake from Photo <Insert Date>" as the name in the DB.
3. In the Food Summary, and in any reports in the Admin Tool, we display the name as "Intake from Photo <Insert Date>" 

Would that work?

**Comment by coderReview** [comment]
2- It would just replace the existing food with the latest. I don't know if we would image would get replaced by the latest one. I would have to check.

**Comment by rsial2** [comment]
What if we made it "Intake from Photo 04/14/15 12:05". So we add a timestamp to the food name whenever no food name is entered? This way it's unique. Would that help?

**Comment by coderReview** [comment]
This would add entries to the food list anyway. I would have to change the code to match the same behavior as the audio recording. And this should take a few days as I mentioned.

**Comment by szwart** [comment]
Perfect!



On Apr 14, 2015, at 4:31 PM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


@coderReview<https://github.com/coderReview>, what if we did this:
1. User can add food name or not. Basically, we don't require them to do it.
2. If they don't add the food name, in the DB, we save it as "Intake from Photo " as the name in the DB.
3. In the Food Summary, and in any reports in the Admin Tool, we display the name as "Intake from Photo "

Would that work?

**Comment by szwart** [comment]
That works!



On Apr 14, 2015, at 4:38 PM, Rashid Sial <notifications@github.com<mailto:notifications@github.com>> wrote:


What if we made it "Intake from Photo 04/14/15 12:05". So we add a timestamp to the food name whenever no food name is entered? This way it's unique. Would that help?

**Comment by rsial2** [comment]
@coderReview, ok, once we're done entering the round 8 changes, I'll send you an email so that you can include this in your estimates. Depending on the cost & time, we'll need NASA to approve it.

**Comment by szwart** [comment]
Fixed.
