### ISSUE TITLE
Round 7 - 3rd Party Libraries

### ISSUE THREAD

**Issue by rsial2** [nasa/NTL-ISS-Food-Intake-Tracker#25]
Please update https://github.com/nasa/NTL-ISS-Food-Intake-Tracker/tree/master/Third%20Party%20Libraries with the new libraries that we're using.

**Comment by coderReview** [comment]
How do I add a link to github repository? Should I change it directly in Nasa repository?

**Comment by rsial2** [comment]
Create a text file and then include a link in that text file.

For the locally modified libraries, include the code.

**Comment by coderReview** [comment]
@rsial2 , instead of posting the repository, I will put the code and libraries used. For PGClientKit I will make a small text file on how to recompile the static libraries (libssl, libcrypto and libpq). The only used without modiification is the barcode scanner libary. Is this ok?

**Comment by rsial2** [comment]
Yeah, I'd much prefer the code please :)

**Comment by rsial2** [comment]
@coderReview, just checking in on this. Please let me know if you can complete it soon.

**Comment by coderReview** [comment]
When all issues are fixed, I will update this folder.

**Comment by rsial2** [comment]
I need it soon - please remember that the app itself needs the libraries to be updated too as we discussed before. That was part of it, updating the app to the latest versions and getting the code into GitHub. 

I need this done soon because I have to launch a bug hunt in the next 2 days. Can you do this today or tomorrow?

**Comment by coderReview** [comment]
The app is updated with latest stable version of the Libraries. What I will do is to put the link to the github repository and a deployment guide for each library (possibly some patches, if applicable). What do you think? Or should I move the instructions to the app's DG?

**Comment by rsial2** [comment]
Please move it to the deployment guide please. Want to keep things consolidated.

**Comment by coderReview** [comment]
@rsial2 , Merge request created. Deployment Guide was updated. Also, I made some code cleanup (removed openears reference).

**Comment by rsial2** [comment]
Thanks @coderReview!

FYI, @nasarader, this is all set. Please see: https://github.com/nasa/NTL-ISS-Food-Intake-Tracker/tree/master/Third%20Party%20Libraries
