### ISSUE TITLE
Round 8 - Admin Tool - Bulk Upload Does Not Upload All Foods

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#26]
There are 2 Mashed Potatoes items in the data.csv file, one is Russian and one is NASA.  When I searched the Food Data in the Admin Tool, there were 2 Mashed Potatoes, but both were the Russian version (with 923 mg sodium).  I deleted one of the entries and did a bulk upload to upload our data.csv file.  I then went back to the Food Data tab of the Admin Tool and searched for Mashed Potatoes and the Russian version with 923 mg sodium is still the only one that appears.  I noticed that the data.csv file has 504 entries and the Admin Tool Food Data tab shows that there are 502 entries. Is this a problem that we have 2 foods with the same exact name?

**Comment by coderReview** [comment]
Yes. The first one is updated with the information of the second one. I could add a check for both food name and origin when doing bulk load. Is there any other information that might make the food unique besides name and origin?

**Comment by szwart** [comment]
If that is the issue, then we can just add the origin to the name of the food item - use "Russian Mashed Potatoes" or "NASA Mashed Potatoes".  There are only a couple foods that have the exact name and the only identifier is the origin.  Thanks.

**Comment by coderReview** [comment]
That is not needed. I can make the separation based on both food name and origin. I will have to update the Admin Tool. Not sure if any change in the iPad application is needed.

**Comment by szwart** [comment]
OK - but when the user sees the 2 Mashed Potato items in the Food Inventory list, they can't distinguish them (unless they actively sort by origin), so we will likely add the origin to those food names anyway just to make it easier for the user.

**Comment by coderReview** [comment]
I think in the iPad application this could be done only for duplicate food. Otherwise the list will become very poluted with food name and origin. In the database the food name does not need to have the origin. Also, I could also update the admin tool to add a column with the origin in the food tab.

**Comment by szwart** [comment]
I only added (NASA) or (Russian) after the food if it had a duplicate name.  So there are only a handful of these.  I do not think it looks cluttered.  If I click the Food Data tab in the Admin Tool, there is an entry for origin.  Unless you think we need to adjust the Admin Tool, I think it is ok and this issue is closed.

**Comment by coderReview** [comment]
Since the origin is already present in the database, to have it in the name is not really necessary and could lead to errors in the future (forget to add it). A quick change in the admin tool can fix this. 
In the iPad app I would add the origin to those food with duplicate name in the add consumption screen. This wouldn't take a long time either.
One other option is to change just the admin tool and add the origin to the name automatically when a record with the same name is already found.

**Comment by rsial2** [comment]
@szwart, does this option work for you?

Option: One other option is to change just the admin tool and add the origin to the name automatically when a record with the same name is already found.

**Comment by szwart** [comment]
Yes, that works for us.  Thanks!

**Comment by coderReview** [comment]
Hi, I think the first option might best.
1- The update in the admin tool is very simple.
2- The update in the app tool doesn't take long (would only update the add food screen).

Why first option is best?
1- User does not have to care about food with same name
2- After the food is added and name gets changed, if you need to update the food you will have to add the origin in the name inside the CSV file othewise it will add a new food

If you want I will make the necessary changes and send you the ipa. If it looks good I commit to repository.

**Comment by szwart** [comment]
OK - as long as the user can distinguish food items with the same name, I defer to whatever you think is best.

**Comment by szwart** [comment]
Going forward, we are going to add food origin in parentheses after any food with the same name. Otherwise, the food inventory still does not distinguish between 2 foods of the same name but different origin.  This is not a problem for us and we consider this fixed.

**Comment by coderReview** [comment]
@szwart, there is no need for that. Both Admin tool and iPad are able to distinguish food with same name but different origin. If you are having any issue, let me know and I will fix that.
Thanks
