### ISSUE TITLE
Round 8 - Snap a Photo - Cancel

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#27]
When the Snap a Photo button is tapped, then Cancel, then it asks the user are they sure they want to cancel.  If the user taps Yes, they still have to tap Cancel again to actually cancel.  Can we make it so that when the user taps Cancel the first time, it brings them straight back to the Daily Intake Report page (so get rid of the pop up that asks to confim the cancel and the second cancel step)?

**Comment by coderReview** [comment]
@szwart, Do you agree with the following?
1- I will remove the popup.
2- If you hit Cancel, it will enable all bottom buttons (Result, Show all photos, Cancel)
3- If you hit bottom Cancel you will go back to intake list
4- If you take a photo, you can click the bottom cancel to go back to intake list.

**Comment by szwart** [comment]
No, we would like to have it so that if the user taps Cancel, it immediately brings them back to the Daily Intake Report page.

**Comment by coderReview** [comment]
@szwart, Will you still want to support the results, all photos buttons?

**Comment by szwart** [comment]
Sorry.  What you suggested above is probably best (to enable all bottom buttons once Cancel is pressed once.  We were just trying to figure a way that if the user wants to get out of the camera screen, they could do it with the press of one button.  Similar to the check box food area - there is a Go Back button at the top left.  Could that be done here?  If that is pressed, the user goes directly back to the Daily Intake Report.

**Comment by rsial2** [comment]
Hi Sara, we completed the update already - I just need to create a new build of the app. After testing if you still want it changed to what you mentioned in the comment above, just add another comment here.

**Comment by coderReview** [comment]
These buttons will only be enable after a photo (or barcode) is taken. As Rashid said, try how I implemented, if you think you have to change it let me know. Thanks

**Comment by szwart** [comment]
This works for us.  Thanks!
