### ISSUE TITLE
Round 8 - Daily Intake Report/Food Inventory - Change to Title Case

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#31]
Change "DAILY INTAKE REPORT" to "Daily Intake Report".
Change "TODAY'S NUTRIENT INTAKE PROGRESS" to "Today's Nutrient Intake Progress"
In Food Inventory page, change "FOOD INVENTORY" to "Food Inventory"
In Food Inventory page, change "CATEGORIES" to "Categories"
After the microphone button is tapped, change the "RECORD FOOD INTAKE" at the top of the screen to "Record Food Intake"

**Comment by coderReview** [comment]
The font used puts all text to caps. Should I use another font? Which?

**Comment by rsial2** [comment]
You're good to replace it. Just use the closest font possible so that it looks similar.

**Comment by szwart** [comment]
Fixed
