### ISSUE TITLE
Round 8 - Help / Settings - Update with current user guide

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#34]
Many of the screenshots and icons used in the Help / Settings area are old and have been updated.  Can we update this with the user guide that was recently updated?

**Comment by coderReview** [comment]
Where can I get the current user guide?

**Comment by rsial2** [comment]
I will post it tomorrow. It's still being updated :)

**Comment by rsial2** [comment]
@coderReview, the updated user guide has been committed to GitHub: https://github.com/nasa/NTL-ISS-Food-Intake-Tracker/blob/master/App%20Documentation/User_Guide/ISS_FIT_User_Guide.doc

**Comment by coderReview** [comment]
Right now the help data is in Html. Do you want to show the user guide as an Html or can I convert to pdf and show it like that?

**Comment by rsial2** [comment]
HTML please.

**Comment by rsial2** [comment]
Just follow the current implementation so that it looks the same, please.

**Comment by szwart** [comment]
Fixed
