### ISSUE TITLE
Round 8 - Login Screen - Change Register Button

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#35]

**Comment by szwart** [comment]
Rename "Register" as "New User" and use a plus sign instead of the current icon that looks like a person.

**Comment by rsial2** [comment]
@coderReview, here's the icon you can use for the app: http://www.flaticon.com/free-icon/add-plus-button_61112

Just make sure to follow the attribution procedures (as specified on the link above).

**Comment by rsial2** [comment]
@coderReview, "Regiser" needs to be changed to "New User". The new icon is there, but the label needs to be updated.

**Comment by szwart** [comment]
Fixed.
