### ISSUE TITLE
Round 8 - Daily Intake Report - Change First Add Food Icon

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#36]
Change the icon that is currently a circle with a check in it to a folder with a plus on it. When the button is tapped, it should change to a lighter color (similar to what happens when the camera icon it tapped).

![g59_add](https://cloud.githubusercontent.com/assets/11872594/7266253/92315844-e86c-11e4-9d55-fe422b302880.gif)

**Comment by rsial2** [comment]
When the Add Food button is tapped, the Food Inventory page immediately loads, there's no press state (change in color).

**Comment by szwart** [comment]
It looked like it changed a shade on my iPad...but it's fine not changing either.  Basically, just want to keep it as it is now (just change the icon).

**Comment by rsial2** [comment]
@coderReview, please use this icon: http://www.flaticon.com/free-icon/new-add-folder_8715

**Comment by coderReview** [comment]
@szwart , @rsial2 , Is this fixed?

**Comment by rsial2** [comment]
@coderReview, Sara is waiting on another team at NASA to provide feedback. Please hold tight.

**Comment by szwart** [comment]
Approved!
