### ISSUE TITLE
Round 8 - Daily Intake Report - Change Logout Icon

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#37]
Change the Logout icon to the one attached here.  When the button it tapped, it should appear lighter in color (similar to what the camera icon looks like when that button is tapped).
![g63_logout](https://cloud.githubusercontent.com/assets/11872594/7266336/80a20b9a-e86d-11e4-8a98-670832455e15.gif)

**Comment by rsial2** [comment]
When the logout button is tapped, there's an immediate logout, there's no press state (change in color).

**Comment by szwart** [comment]
Oops.  You are right!

**Comment by rsial2** [comment]
@coderReview, here's the icon you can use for the app: http://www.flaticon.com/free-icon/key-silhouette-security-tool-interface-symbol-of-password_56255

Just make sure to follow the attribution procedures (as specified on the link above).

**Comment by coderReview** [comment]
@szwart , @rsial2 , Is this one fixed?

**Comment by rsial2** [comment]
@coderReview, Sara is waiting on another team at NASA to provide feedback. Please hold tight.

**Comment by szwart** [comment]
Approved!
