### ISSUE TITLE
Admin Tool - Add Login Capability

### ISSUE THREAD

**Issue by rsial2** [nasa/NTL-ISS-Food-Intake-Tracker#40]
Please implement the following:

1. Add login capability to the admin tool.

2. Make a default login, and then make the login configurable via the admin tool setup process.

3. Update the architecture and deployment guide so that it includes information about the new functionality, and how to configure it.

**Comment by coderReview** [comment]
@rsial2 , done. See merge request #44.

**Comment by szwart** [comment]
Fixed
