### ISSUE TITLE
Admin Tool - Report Not Functioning

### ISSUE THREAD

**Issue by rsial2** [nasa/NTL-ISS-Food-Intake-Tracker#42]
The admin tool doesn't seem to be working if you run a report. The page will refresh but nothing is loaded.

**Comment by coderReview** [comment]
Latest pull request has the fix for this issue.
Thank you.

**Comment by rsial2** [comment]
I just ran a report (both user and all user) and the summary.zip was generated, but the .zip file is empty (there is no csv file).

**Comment by coderReview** [comment]
@rsial2 , when I merged the data from NASA I might have wiped out all food consumption records. So they might be empty alright. Can you try adding some records and see if they are still empty? Thanks

**Comment by rsial2** [comment]
Found a few issues:
1. If you login as the Jack O'Neil user, and go to julian date 114, there is data saved - so the report is not pulling that data.
2. If you add data right now (and I just did that for today, Jack O'Neil user), the food will be added, but the "last sync" timestamp is not being updated - so the data is not being synced / saved.

**Comment by coderReview** [comment]
@rsial2 , I had no issue with synced data. Last sync worked ok. Merge request has fix for this issue.
Thanks

**Comment by rsial2** [comment]
I just tested it, and the report is working. But the summary.csv is not accurate.

1. For the Jack user, I entered 7 foods. All were successfully synced.
2. The media for the food were all correctly saved, and showed up in the zip file.
3. When viewing the summary.csv, all foods appeared in the report.
4. ERROR: Date stamp is appearing as 04/24 or 04/25, even though I entered the food for a date in the future, which is 04/26.
5. ERROR: Timestamp for "Intake from Photo" is showing as 18:27:00, when it was entered at 15:36:00.
6. ERROR: Timestamp for "Intake From Photo" & "Drinking Water" is showing as 00:00:00, when it was entered at 15:36:00.

See screenshot: 
![image](https://cloud.githubusercontent.com/assets/5807576/7395120/f16871e0-ee65-11e4-818a-29f186ab56db.png)

**Comment by rsial2** [comment]
Actually, here's a bigger screenshot: 
![image](https://cloud.githubusercontent.com/assets/5807576/7395130/061797ba-ee66-11e4-8aac-b33f790460c5.png)

**Comment by rsial2** [comment]
@coderReview, can you look into this today?

**Comment by coderReview** [comment]
@rsial2 , I think it's all ok.
Let's see. Day 115 is 04/25 - saturday.
The items in the app in order and its correspondence to the excel summary file:
1- Almonds, Emerald ... -> Line 15
2- Almonds, Unsalted -> Line 16
3- Intake from voice -> Line 19
4- Intake from Photo -> Line 20
5- Drinking water -> Line 21
6- Blueberry/Raspberry ... -> Line 18

All the times are the same.

**Comment by rsial2** [comment]
Ok, but what about these issues?
1. Line 20, time stamp is being displayed as 00:00:00, when it was entered at 15:36:00.
2. Line 21, time stamp is being displayed as 00:00:00, when it was entered at 15:36:00.

Also, is the "+0000" required? If not, let's remove it.

**Comment by coderReview** [comment]
The time in the report is the same as in the application. So if there is an issue is not with the report but how the date is saved in the food record. The hour/minute/second information could be missing. Will check and update the iPad app.

**Comment by rsial2** [comment]
Thanks for looking into it.

**Comment by rsial2** [comment]
If you can make a fix today, I would appreciate it. I would like to launch a bug hunt contest (for QA) later today. This is the last thing I'm waiting on :)

**Comment by coderReview** [comment]
@rsial2 , Fixed in latest merge request.

**Comment by rsial2** [comment]
Found two issues:

1. In latest build, all profile photos are missing now.

2. Ran a summary for the Jack user, now all food entries for yesterday and today, have the exact same  entry time, even though the times should be different:
![image](https://cloud.githubusercontent.com/assets/5807576/7420515/22e20f84-ef4b-11e4-949f-423fdc76124c.png)

**Comment by coderReview** [comment]
I made a clean up in the database. There are only entries I've made.

**Comment by rsial2** [comment]
I don't understand. Were the photos cleared from the DB? How does that explain the time stamps though?

**Comment by rsial2** [comment]
I checked the latest build. Here are the issues:
1. Photos taken via the app are not being sized correctly. They distorted. You had fixed this one before. They're distorted again.
2. I tried to register a new user to see if the distortion would appear, and during registration, the camera wouldn't load.
3. See attached photo. I entered food for Julian date 123, which is 05/03/15 for the Jack user. I found the following issues:
-----I added 4 foods for JD 123, but they are showing up as 05/01/15, and not 05/03/15
-----It really looks like the report is working off of the date of the device, and not the date entered / selected by the user.

**Comment by coderReview** [comment]
1- Photos I've added were taken before the fix. So some of them will look strange.
2- Worked fine. See Paulo Silva user. I've just recompiled the code with latest Xcode.
3- Fixed. The report was only generated until the current date plus 1 day. The idea was to generate the report for past entries not future ones. I've changed so past and future (plus 180 days) will be fetched.

**Comment by rsial2** [comment]
1. Ok
2. I figured out the issue. The problem is the iOS version. I was running iOS 8.2, and it wouldn't work. So I upgraded to iOS 8.3, and it worked. The iPads on the ISS will be running iOS 7.X+ and a few will be running iOS 8.X+. Can you fix the camera so it'll work with iOS 7+ plus. 
3. Fixed

**Comment by coderReview** [comment]
2- I don't have an iPad with 7.x anymore. However, nothing in the code was changed that justifies this issue. Anyone has any iPad with this iOS version?

**Comment by rsial2** [comment]
Ok, I'm going to close this defect and we'll see how the members do in the bug hunt.
