### ISSUE TITLE
Round 8 - Admin Tool - Bulk Upload user data.csv file

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#43]
A question came up about the file used to bulk upload user profile data.  One of the fields is “Max Packets per Food Product Daily”.  If that number is changed, it doesn’t look like that affects the Qty in the drop down scroll wheel.  Do you know if that Max Packets number changes anything?  We don't necessarily need this field anymore because users don't ever type numbers for Qty (this was originally there to prevent users from typing 33 instead of 3, etc).  Can I delete that column in the User Data.csv file?

**Comment by coderReview** [comment]
@szwart, I will have to update the loadUser.py script to adapt to this request and update the site instructions and Admin Tool documentation. 
@szwart, @rsial2 , Do you want me to implement these changes?

**Comment by szwart** [comment]
No, if it's a big deal let's not change anything.  It's not hurting anything right now.  I just wasn't sure if it was actually being used for anything. We will likely upload crew profiles manually anyway instead of using the bulk upload feature.

**Comment by rsial2** [comment]
Ok, thanks Paulo & Sara. I am closing this ticket.
