### ISSUE TITLE
Round 9 - Help / Settings - this needs to be updated with current screen shots

### ISSUE THREAD

**Issue by szwart** [nasa/NTL-ISS-Food-Intake-Tracker#47]
It was pointed out that the screen shots in the Help / Settings area are not current with the new icons and colors.  Can this be fixed easily in this round??

**Comment by rsial2** [comment]
Yes, but it'll need to be part of round 9, since the help doc and the help content within the app were already updated before the icon change requests came in.

**Comment by rsial2** [comment]
Completed.
