### ISSUE TITLE
Round 9 - Lost Internet Connection

### ISSUE THREAD

**Issue by rsial2** [nasa/NTL-ISS-Food-Intake-Tracker#48]
Please change the message to:
Title: Network Connection Error
Body: This iPad has lost it's network connection. You can still use the ISS FIT app, and we will attempt to sync with the central food database when it's available.

**Comment by rsial2** [comment]
And for when it reconnects, please change it to:
Title: Connection Re-established
Body: This iPad now has a network connection. Any food that you've entered will now be saved to the database.

**Comment by rsial2** [comment]
@derekargueta, the prompt now states "when it's available.it's available". Please change it to "when it's available."

**Comment by derekargueta** [comment]
@rsial2 woops, forgot to delete a line. Opened up a new PR with that fix, and also with a generic .gitignore file for the project to ignore all user-specific data from git tracking.

**Comment by rsial2** [comment]
Looks good, thanks!
