### ISSUE TITLE
Add .gitignore to ignore standard XCode user files and data.

### ISSUE THREAD

**Issue by derekargueta** [nasa/NTL-ISS-Food-Intake-Tracker#64]
When working on issue #48 I was surprised that git added some xcuserdata files. These should be ignored through a .gitignore file.

http://stackoverflow.com/questions/18939421/what-should-xcode-6-gitignore-file-include

**Comment by rsial2** [comment]
@coderReview, do you agree with this assessment?

**Comment by coderReview** [comment]
@rsial2 I see no problem in ignoring these files. They are user related and recreated when the Xcode project is open.

**Comment by rsial2** [comment]
Thanks, I've approved the merge request and will test.
